[package]
name = "rustvision"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/H1ghBre4k3r/rustvision"
authors = ["H1ghBre4k3r"]
license = "LGPL-3.0"
keywords = ["computervision", "graphics"]

[dependencies]
